name: couchclient
version: 0.1.0
description: >
  A Couchbase client library written in Dart language.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  #memcached_client:
  unittest:
  logging:
